### ISSUE TITLE
Replacing pwasm-abi-derive as RPC mechanism

### ISSUE THREAD

**Issue by geigerzaehler** [oscoin/oscoin-parity-wasm-prototype#41]
We are exposing the ledger as an Ethereum ABI with the `Ledger` trait. The client uses this ABI to call into the ledger. For this project the Ethereum ABI only serves as an RPC mechanism between client and ledger. Other benefits, like interoperability with other contracts are unused. On the ledger side we use `pwasm-abi` and `pwasm-abi-derive` to provide an Ethereum ABI for the ledger.

### Problem

The use of an Ethereum ABI as the RPC mechanism is problematic. For example only a few fixed type can be returned from getters. This makes it impossible to expose `get_project() -> Option<Project>` with the ABI. The same holds for transaction call arguments.

In addition `pwasm-abi-derive` causes some issues as described in #37.

### RPC requirements

We have a trait that defines the interface that the ledger exposes to users. Users are provided the interface through the client. We need a library that provides or generates the code that constructs an RPC call on the client side and dispatches a call on the Ledger side.

For example

```rust

#[rpc]
pub trait Ledger {
  // ...
}

pub fn call () {
  // ...
  let res: Vec<u8> = rpc.dispatch(ledger_impl, pwasm_ethereum::input())
  pwasm_ethereum::ret(res);
}
```

### Solutions

`pwasm-abi` provides everything but user defined types. I’m currently investigating other solutions

**Comment by cloudhead** [comment]
https://github.com/google/tarpc is the only one I know of - but haven't used it.

**Comment by geigerzaehler** [comment]
I’ve had a look at `tarpc`. It is a full fledged RPC framework and it does not provide APIs that fit our narrow use case. Moreover we cannot compile it with `no_std`.
