### ISSUE TITLE
Implement project listing

### ISSUE THREAD

**Issue by rockbmb** [oscoin/oscoin-parity-wasm-prototype#64]
This issue is about implementing the ability for a user to query the ledger for the projects they are members of.

The end result should be a new `Client` method:

```rust
impl Client {
...
    fn list_projects(&self, user: AccountId) -> QueryResult<Vec<oscoin_ledger::Project>>
...
}
```

**Comment by cloudhead** [comment]
That's how user accounts are identified :relaxed:

**Comment by cloudhead** [comment]
By the way I don't think it makes sense for this functionality to be implemented in the ledger, based on our recent discussions. This would require a reverse index for every single account.

**Comment by geigerzaehler** [comment]
I was under the assumption that we want to list _all_ projects. Not only the ones that a user is a member of. Could you confirm @xla?

**Comment by cloudhead** [comment]
Ah, yes that would make more sense, hence @xla 's question.

**Comment by xla** [comment]
Exactly, and if not done in the ledger we have to start the conversation where such indexes would live and how we can guarantee availability of them.

**Comment by cloudhead** [comment]
This stuff will be available in the ledger :+1:

**Comment by rockbmb** [comment]
I was not watching the repository, which is why I was not notified of this discussion...

**Comment by cloudhead** [comment]
> I was not watching the repository, which is why I was not notified of this discussion...

Shouldn't you get notifications for participating/having created this issue?
