### ISSUE TITLE
personal_signtransaction is deprecated

### ISSUE THREAD

**Issue by xla** [oscoin/oscoin-parity-wasm-prototype#70]
When operating the dev not the following warning appears:

`2019-09-19 16:10:38  personal_signTransaction is deprecated and will be removed in future versions: Account management is being phased out see #9997 for alternatives.`

Wanted to flag this for consideration wrt account handling.

**Comment by rockbmb** [comment]
@xla thanks for raising the issue. @geigerzaehler and I were already aware of this, but it is still unclear how it can be handled. Especially with this being a prototype that may or may not continue to be used.

For now it works, but if we remain with this project we can look into moving on from the use of this feature.
